server:
  port: 9001

spring:
  application.name: USER-SERVICE

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    region: defaultRegion
    availability-zones:
      defeaultRegion: localZone, raspberryZone
    service-url:
      localZone: http://localhost:8761/eureka/
      raspberryZone: ${eureka_url:http://192.168.0.69:8761/eureka}
  instance:
    instance-id: ${spring.application.name}:${server.port}
    hostname: ${eureka_host:localhost}
