server:
  port: 9001


spring:
  application.name: USER-SERVICE
  cloud:
    inetutils:
      preferred-networks:
        - 192.168

eureka:
  instance:
    prefer-ip-address: true
    #hostname: 192.168.0.69
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defeaultZone: http://192.168.0.69:8761/eureka

