server:
  port: 9001

spring:
  application.name: USER-SERVICE

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${eureka_url:http://192.168.0.69:8761/eureka}
  instance:
    instance-id: ${spring.application.name}:${server.port}
    hostname: ${eureka_host:localhost}
