POST {{host}}/user/signIn
Content-Type: application/json

{
  "email": "pascal@butterbach.org",
  "password": "the-password"
}
> {%
     client.global.set("access_token", response.body["access_token"]);
     client.global.set("refresh_token", response.body["refresh_token"]);
  %}


### VALIDATE TOKEN
POST {{host}}/token/validateToken
Authorization: Bearer {{access_token}}


### REFRESH ACCESS WITH REFRESH TOKEN
POST {{host}}/token/
Authorization: Bearer {{refresh_token}}

> {%
     client.global.set("access_token", response.body["access_token"]);
     client.global.set("refresh_token", response.body["refresh_token"]);
  %}


### REVOKE REFRESH TOKEN
PUT {{host}}/token/
Authorization: Bearer {{refresh_token}}


### REGISTER NEW USER
POST {{host}}/user/
Content-Type: application/json

{
  "user_name": "teasdasdasdst",
  "email": "yyys@butterbach.org",
  "password": "teadsasdasdst"
}

> {%
     client.global.set("access_token", response.body["access_token"]);
     client.global.set("refresh_token", response.body["refresh_token"]);
  %}


### UPDATE USER
PUT {{host}}/user/
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "email": "pascal@butterbach.org",
  "password": "the-password",
  "new_email": "pascal@butterbach.org",
  "new_password": "1234",
  "new_password_repeated": "1234",
  "new_username" : "Opfer"
}


### DELETE USER
DELETE {{host}}/user/42
Authorization: Bearer {{access_token}}








